version: "3.9"

name: todo-stack

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:16-alpine
    container_name: todo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-Asia/Tokyo}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "${HOST_DB_PORT:-15432}:5432"   # ← IDEから直でつなぐ用（任意）
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    restart: unless-stopped
    environment:
      # DB接続（Composeで組み立て）
      DB_URL: jdbc:postgresql://${DB_HOST}
