version: "3.9"

name: todo-stack

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:16-alpine
    container_name: todo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    restart: unless-stopped
    environment:
      # Spring DataSource（application.yml から参照）
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Spring profile（Dockerfileでprodにしているが上書き可能）
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      # タイムゾーン & JVM設定（必要に応じ調整）
      TZ: Asia/Tokyo
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "${APP_PORT:-18090}:8080"
    networks:
      - appnet
